---
- name: Start lighthouse service
  become: true
  ansible.builtin.service:
    name: lighthouse
    state: started

- name: Restart lighthouse service
  become: true
  ansible.builtin.service:
    name: lighthouse
    state: restarted
